PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

app_xml:
    resource: "routing/app.xml"

app_yml:
    resource: "routing/app.yml"

app_annotation:
    resource: "@AcmeAppBundle/Controller/"
    type:     annotation
