
services:

    my.sitemap.listener:
        class: Acme\AppBundle\Listener\SitemapListener
        arguments:
            - "@doctrine"
            - "@router"
        tags:
            - { name: "kernel.event_subscriber" }
